### ISSUE TITLE
Rapidly updating causes memory leaks

### ISSUE THREAD

**Issue by newtask** [cytoscape/cytoscape.js-navigator#35]
In my webapp I change the cytoscape data each second. The navigator creates for each render a base64 image via cytoscape and replaces the img.src with the new string. The problem is, that the old image stays in memory. 

Maybe there is a better way to update the image instead of changing the img.src.

Testet on Chrome, 1h = ~ 1GB memory when updating the image every second 

Found in "_updateThumbnailImage"

```

      if( png.indexOf('image/png') < 0 ){
        img.removeAttribute( 'src' );
      } else {
        img.setAttribute( 'src', png );
      }
```

**Comment by maxkfranz** [comment]
It doesn't look like the previous png is referenced anywhere.

You may just be noticing that Chrome increases the amount of reserved memory it has based on its own heuristics.  That doesn't necessarily mean that the memory is actually in use.

**Comment by newtask** [comment]
Well, the chrome tab crashes after some time, when there is no more memory left. That does not occur when I disable the navigator. It might be a browser problem but maybe there is a better way for displaying the image.

Did you try updating the cytoscape data every second and let the code run for 1 or 2 days?

Here is a link where someone else discovered the memory problem with base64 images: [Quickly updating the image with Data URI causes caching, a memory leak](https://hk.saowen.com/a/04ca6f1cf771f7a7f0999b6577e56fe28e65b6e54015866d59e3450ca49816bd)

**Comment by maxkfranz** [comment]
The only thing I can think of for img is to use a blob export and blob URIs in the src of the img.  However, Cytoscape uses base64 => blob for `output: 'blob'` to support IE9.  So the blob case would have to be detected separately and use feature detection to go directly to a blob.  Then the extension could be updated to use the blob.  I'm not sure if this would work or whether the browser would also cache the blobs.

Another option is to add a `cy.canvas()` export, similar to `cy.png()`.  The `canvas` could be an optional input parameter (for canvas re-use).  The extension then could use a canvas instead of an img.  Probably this would work.

If you have time to try and make PRs for either of these, that would be great.  If not, it may make sense to not use this extension for now if it's incompatible with your app.
